# Тестовые данные
GET http://localhost:3123/api HTTP/1.1

###

# Пользователи
## Регистрация пользователя

POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "test@overlook5.net",
  "name": "Jack",
  "password": "password",
  "isPro": true
}

###

# Пользователи
## Авторизация пользователя

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "test@overlook5.net",
  "password": "password"
}

###

# Пользователи
## Проверка состояния пользователя

GET http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3RAb3Zlcmxvb2s1Lm5ldCIsImlkIjoiNjNlMGI2ZWIxMDk0ZDFmMWU3ZmZkNjU4IiwiaWF0IjoxNjc1NjcxMzY5LCJleHAiOjE2NzU4NDQxNjl9.tA_RBhWNcc-WOQ4LYs9YrGN1CCfyP7SSBHlKwrDwn3Q


###

# Предложения
## Получение списка предложений

GET http://localhost:5000/offers/ HTTP/1.1
Content-Type: application/json

###

# Предложения
## Получение 2х предложений из списка

GET http://localhost:5000/offers/?limit=2 HTTP/1.1
Content-Type: application/json

###

# Предложения
## Создание предложения

POST http://localhost:5000/offers/ HTTP/1.1
Content-Type: application/json

{
  "title": "some short title",
  "date": "2022-05-12T11:56:37.573Z",
  "city": {
    "name": "Cologne",
    "location": {
      "latitude": 50.938361,
      "longitude": 6.959974
    }
  },
  "previewImage": "imagePath",
  "isPremium": true,
  "rating":  3,
  "type": "Room",
  "price": 36556,
  "description": "Много места, но темно",
  "images": ["imagePath1", "imagePath2"],
  "bedrooms": 4,
  "guests": 2,
  "goods": ["Breakfast", "Washer"],
  "host": "63d2588093ede432719fcb12",
  "location": {
    "latitude": 53.550341,
    "longitude": 10.000654
  }
}

###

# Предложения
## Получение детальной информации о предложении

GET http://localhost:5000/offers/63d2588093ede432719fcb14 HTTP/1.1
Content-Type: application/json

###


# Предложения
## Редактирование предложения

PATCH http://localhost:5000/offers/63d2588093ede432719fcb67 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3RAb3Zlcmxvb2s1Lm5ldCIsImlkIjoiNjNlMGI2ZWIxMDk0ZDFmMWU3ZmZkNjU4IiwiaWF0IjoxNjc1NjcxMzY5LCJleHAiOjE2NzU4NDQxNjl9.tA_RBhWNcc-WOQ4LYs9YrGN1CCfyP7SSBHlKwrDwn3Q

{
  "title": "some short title new",
  "description": "Много места, но очень темно new"
}

###

# Предложения
## Удаление предложения

DELETE http://localhost:5000/offers/63d267a23805913a8ca72d57 HTTP/1.1
Content-Type: application/json

###

## Список комментариев к объявлению
GET http://localhost:5000/offers/63d2588093ede432719fcb67/comments HTTP/1.1

###

## Создать комментарий
POST http://localhost:5000/comments HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3RAb3Zlcmxvb2s1Lm5ldCIsImlkIjoiNjNlMGI2ZWIxMDk0ZDFmMWU3ZmZkNjU4IiwiaWF0IjoxNjc1NjcxMzY5LCJleHAiOjE2NzU4NDQxNjl9.tA_RBhWNcc-WOQ4LYs9YrGN1CCfyP7SSBHlKwrDwn3Q

{
  "comment": "Как обстоят дела с коробками? Как обстоят дела с коробками?",
  "rating": 3,
  "offerId": "63d2588093ede432719fcb14"
}

###

## Отправка аватарки пользователю

POST http://localhost:5000/users/62823cb2c5a64ce9f1b50eb6/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

< /Users/tmp/screen.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--
